Finished facebook share button implementation
solidgear/surveyx2018Q4 pull request #6
Opened 2018-11-19 18:32 UTC by Kurolox

The facebook SDK has been implemented in the application, among a button that appears at the end of a survey where the user can share a post through the facebook application when pressed.

However, this has not been tested in a phone without facebook installed, so it's behaviour might be unexpected in said scenario.

2018-11-19 18:51 UTC, jmoh93 approved these changes

2018-11-19 18:56 UTC, jvillafanez requested changes

2018-11-19 18:56 UTC, jvillafanez commented on Surveyx/app/src/main/java/es/academy/solidgear/surveyx/ui/activities/SocialNetworkActivity.java
> +    }
wrong indent

2018-11-19 18:56 UTC, jvillafanez commented on Surveyx/app/src/main/res/layout/activity_social_network.xml
> +            </TableRow>I
`</TableRow>I` ??

2018-11-19 18:56 UTC, jvillafanez commented on Surveyx/app/src/main/res/layout/activity_social_network.xml
> +                    android:padding="2dp" >
Dummy space in `"2dp" >`

2018-11-26 15:18 UTC, Kurolox commented
I've fixed the mentioned issues. Please review the pull request.

2018-11-26 15:29 UTC, jvillafanez approved these changes

2018-11-26 15:32 UTC, merged